MODEL:
  DEVICE: "cuda"
  WEIGHTS: ""
  META_ARCHITECTURE: "GeneralizedRCNN"
  MASK_ON: True
  BACKBONE:
    FREEZE_AT: 0
    NAME: "build_resnet_fpn_backbone"
  RESNETS:
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
  ANCHOR_GENERATOR:
    SIZES: [[16], [32], [64], [128], [256]]  # One size for each in feature map
    ASPECT_RATIOS: [[0.5, 1.0, 2.0]]  # Three aspect ratios (same for all in feature maps)
  RPN:
    IN_FEATURES: ["p2", "p3", "p4", "p5", "p6"]
    PRE_NMS_TOPK_TRAIN: 12000  # Per FPN level
    PRE_NMS_TOPK_TEST: 2000 # Per FPN level
    # Detectron1 uses 2000 proposals per-batch,
    # (See "modeling/rpn/rpn_outputs.py" for details of this legacy issue)
    # which is approximately 1000 proposals per-image since the default batch size for FPN is 2.
    POST_NMS_TOPK_TRAIN: 6000
    POST_NMS_TOPK_TEST: 2000
  ROI_HEADS:
    NAME: "StandardROIHeads"
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
    NUM_CLASSES: 3
    NUM_MASK_CLASSES: 6
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 2
    POOLER_RESOLUTION: 7
  ROI_MASK_HEAD:
    NAME: "MultiMaskRCNNConvUpsampleHead"
    NUM_CONV: 5
    POOLER_RESOLUTION: 14
    CLS_AGNOSTIC_MASK: false
  PIXEL_MEAN: [0, 0, 0]
  PIXEL_STD: [1, 1, 1]
DATASETS: 
  TRAIN: ("yeastmate",)
  TEST: ("yeastmate_val",)
DATALOADER:
  NUM_WORKERS: 16
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.005
  STEPS: (60000, 80000)
  MAX_ITER: 1000000
  CHECKPOINT_PERIOD: 1000
INPUT:
  MIN_SIZE_TRAIN: (400,)
  MAX_SIZE_TEST: 2048
  MAX_SIZE_TRAIN: 400
  MIN_SIZE_TEST: 1608
  MASK_FORMAT: bitmask
TEST:
  EVAL_PERIOD: 1000000
  DETECTIONS_PER_IMAGE: 2500
VIS_PERIOD: 2500